# Generated by Django 3.2.11 on 2022-02-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helloworld', '0003_contactmodel_address_contactmodel_email_contactmodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Addresses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.contactmodel_address',),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Emails',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.contactmodel_email',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Phones',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.contactmodel_email',),
        ),
    ]
