# Generated by Django 3.2.11 on 2022-02-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_aboutus_french_brand_text_french_contactmodel_address_french_contactmodel_email_french_contactmodel_'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_french',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Addresses (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.contactmodel_address_french',),
        ),
        migrations.CreateModel(
            name='Email_french',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Emails (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.contactmodel_email_french',),
        ),
        migrations.CreateModel(
            name='Phone_french',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Phones (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.contactmodel_email_french',),
        ),
    ]
