# Generated by Django 3.2.11 on 2022-03-18 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0027_corpo_data_corpo_data_french_corpo_header_corpo_header_french'),
        ('contact', '0002_address_french_email_french_phone_french'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_da',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Contact Form Data',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.contact_info',),
        ),
    ]
