# Generated by Django 3.2.11 on 2022-02-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Testimonial',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.testimonial_user',),
        ),
        migrations.CreateModel(
            name='Testimonial_Admin',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Testimonial (Admin)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.testimonial_admin',),
        ),
    ]
