# Generated by Django 3.2.11 on 2022-02-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_aboutus_french_brand_text_french_contactmodel_address_french_contactmodel_email_french_contactmodel_'),
        ('Testimonials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial_Admin_french',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Testimonial (Admin) (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.testimonial_admin_french',),
        ),
        migrations.CreateModel(
            name='Testimonial_french',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Testimonial (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.testimonial_user_french',),
        ),
    ]
