# Generated by Django 3.2.11 on 2022-02-20 22:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Upload Image')),
                ('abouttext', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='About Us Text')),
                ('counter1', models.IntegerField(verbose_name='Counter Field 1')),
                ('counter1_name', models.CharField(max_length=50, verbose_name='Counter 1 Text')),
                ('counter2', models.IntegerField(verbose_name='Counter Field 2')),
                ('counter2_name', models.CharField(max_length=50, verbose_name='Counter 2 Text')),
                ('counter3', models.IntegerField(verbose_name='Counter Field 3')),
                ('counter3_name', models.CharField(max_length=50, verbose_name='Counter 3 Text')),
                ('counter4', models.IntegerField(verbose_name='Counter Field 4')),
                ('counter4_name', models.CharField(max_length=50, verbose_name='Counter 4 Text')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='brand_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Company Name')),
            ],
            options={
                'verbose_name_plural': 'Brand Text',
            },
        ),
        migrations.CreateModel(
            name='fileproxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_upload', models.FileField(upload_to='upload', verbose_name='Upload File')),
            ],
        ),
        migrations.CreateModel(
            name='gallery_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_Caption', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Image Caption')),
                ('Image_Tag', models.CharField(max_length=300, verbose_name='Image Tag')),
                ('img', models.ImageField(upload_to='media', verbose_name='Upload Image')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='hero_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Main Text')),
                ('subtext', models.CharField(max_length=200, verbose_name='Sub Text')),
            ],
            options={
                'verbose_name_plural': 'Hero Text',
            },
        ),
        migrations.CreateModel(
            name='home_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Edit Home Page Content')),
            ],
        ),
        migrations.CreateModel(
            name='manageseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=300, verbose_name='Add Keywords')),
            ],
        ),
        migrations.CreateModel(
            name='p_artners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(max_length=300, verbose_name='Partner Name')),
                ('Service_content', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Description')),
                ('Service_subtext', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Sub Text')),
                ('Service_img', models.ImageField(upload_to='media', verbose_name='Upload Image')),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='slider_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Image')),
                ('status', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Slider Image',
            },
        ),
        migrations.CreateModel(
            name='solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(max_length=300, verbose_name='Service Name')),
                ('Service_content', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Description')),
                ('Service_subtext', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Sub Text')),
                ('Service_img', models.ImageField(upload_to='media', verbose_name='Upload Image')),
            ],
            options={
                'verbose_name_plural': 'Solutions',
            },
        ),
        migrations.CreateModel(
            name='Sub_Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(max_length=300, verbose_name='Solution Name')),
                ('Service_content', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Description')),
                ('Service_subtext', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Sub Text')),
                ('Main_Service', models.CharField(max_length=200, verbose_name='Main Service Name (Case Sensitive)')),
                ('Info_Text', tinymce.models.HTMLField()),
                ('Icon_set1', models.CharField(help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Icon 1')),
                ('Icon_set1_text', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Icon 1 Text')),
                ('Icon_set2', models.CharField(help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Icon 2')),
                ('Icon_set2_text', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Icon 2 Text')),
                ('Icon_set3', models.CharField(help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Icon 3')),
                ('Icon_set3_text', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Icon 3 Text')),
                ('Icon_set4', models.CharField(help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Icon 4')),
                ('Icon_set4_text', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Icon 4 Text')),
            ],
            options={
                'verbose_name_plural': 'Sub Solutions',
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='testimonial_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info_text', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Change Intro Text on Testimonials')),
            ],
            options={
                'verbose_name_plural': 'Testimonial(Admin)',
            },
        ),
        migrations.CreateModel(
            name='testimonial_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_img', models.ImageField(upload_to='user', verbose_name='Upload Image')),
                ('user_name', models.CharField(max_length=200, verbose_name='Name')),
                ('user_designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('user_review', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Review / What they Say')),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='videodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon_Name', models.CharField(help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Set Icon')),
                ('Icon_Text', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Set Text')),
                ('Icon_subtext', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Set Description')),
            ],
        ),
        migrations.CreateModel(
            name='videogallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_Gallery', models.CharField(max_length=300, verbose_name='Video URL')),
                ('Video_Thumbnail', models.ImageField(upload_to='video_upload', verbose_name='Upload Video Thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='whatwedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_we_do_main', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Main Text')),
                ('what_we_do_sub', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Short Description')),
            ],
            options={
                'verbose_name_plural': 'What We Do',
            },
        ),
    ]
