# Generated by Django 3.2.11 on 2022-02-20 22:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(max_length=300, verbose_name='Solution Name')),
                ('Service_content', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Description')),
                ('Service_subtext', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Sub Text')),
                ('Main_Service', models.CharField(max_length=200, verbose_name='Main Service Name (Case Sensitive)')),
                ('Info_Text', tinymce.models.HTMLField()),
                ('Icon_set1', models.CharField(help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Icon 1')),
                ('Icon_set1_text', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Icon 1 Text')),
                ('Icon_set2', models.CharField(help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Icon 2')),
                ('Icon_set2_text', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Icon 2 Text')),
                ('Icon_set3', models.CharField(help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Icon 3')),
                ('Icon_set3_text', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Icon 3 Text')),
                ('Icon_set4', models.CharField(help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Icon 4')),
                ('Icon_set4_text', tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Icon 4 Text')),
            ],
            options={
                'verbose_name_plural': 'Sub Partners',
            },
        ),
    ]
