# Generated by Django 3.2.11 on 2022-02-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_sub_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactModel_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=400, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='contactModel_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_mail', models.CharField(max_length=200, verbose_name='E-Mail')),
            ],
        ),
        migrations.CreateModel(
            name='contactModel_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=100, verbose_name='Mobile Number')),
            ],
        ),
    ]
