# Generated by Django 3.2.11 on 2022-02-21 05:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_contactmodel_address_contactmodel_email_contactmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='Service_subtext',
            field=tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Index Page Text'),
        ),
    ]
