# Generated by Django 3.2.11 on 2022-02-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_navoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='navoptions_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nText', models.CharField(max_length=100)),
                ('nLink', models.CharField(max_length=100)),
            ],
        ),
    ]
