# Generated by Django 3.2.11 on 2022-02-23 19:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0007_navoptions_french'),
    ]

    operations = [
        migrations.CreateModel(
            name='part_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Main Text')),
                ('subtext', models.CharField(max_length=200, verbose_name='Sub Text')),
                ('img', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Partners Headers',
            },
        ),
        migrations.CreateModel(
            name='part_text_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Main Text')),
                ('subtext', models.CharField(max_length=200, verbose_name='Sub Text')),
                ('img', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Partners Headers(French)',
            },
        ),
        migrations.CreateModel(
            name='sol_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Main Text')),
                ('subtext', models.CharField(max_length=200, verbose_name='Sub Text')),
                ('img', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Solution Headers',
            },
        ),
        migrations.CreateModel(
            name='sol_text_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Main Text')),
                ('subtext', models.CharField(max_length=200, verbose_name='Sub Text')),
                ('img', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Solution Headers(French)',
            },
        ),
        migrations.AddField(
            model_name='hero_text',
            name='img',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero_text_french',
            name='img',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='p_artners',
            name='Service_icon',
            field=models.CharField(default=0, help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Choose Icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='p_artners_french',
            name='Service_icon',
            field=models.CharField(default=0, help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Choose Icon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub_partners',
            name='Icon_set4',
            field=models.CharField(blank=True, help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Icon 4'),
        ),
        migrations.AlterField(
            model_name='sub_partners',
            name='Icon_set4_text',
            field=tinymce.models.HTMLField(blank=True, help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Icon 4 Text'),
        ),
        migrations.AlterField(
            model_name='sub_solutions',
            name='Icon_set4',
            field=models.CharField(help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, null=True, verbose_name='Icon 4'),
        ),
        migrations.AlterField(
            model_name='sub_solutions',
            name='Icon_set4_text',
            field=tinymce.models.HTMLField(help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", null=True, verbose_name='Icon 4 Text'),
        ),
    ]
