# Generated by Django 3.2.11 on 2022-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0008_auto_20220223_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='Service_icon',
            field=models.CharField(default=0, help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Choose Icon'),
            preserve_default=False,
        ),
    ]
