# Generated by Django 3.2.11 on 2022-02-24 17:10

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0009_solutions_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_solutions',
            name='Icon_set4',
            field=models.CharField(blank=True, default=0, help_text="For complete cheatsheet of available icons , visit <a href='https://boxicons.com/cheatsheet' target='_blank'>Here</a>", max_length=100, verbose_name='Icon 4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub_solutions',
            name='Icon_set4_text',
            field=tinymce.models.HTMLField(blank=True, default=0, help_text="To Upload an Image , Host it on <a href='https://imgbb.com/' target='_blank'>imgbb.com</a> for free ! and paste the Share URL here.", verbose_name='Icon 4 Text'),
            preserve_default=False,
        ),
    ]
