# Generated by Django 3.2.11 on 2022-02-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0010_auto_20220224_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_solutions',
            name='Service_subtext',
        ),
    ]
