# Generated by Django 3.2.11 on 2022-02-25 09:40

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0012_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='Job_Description',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
    ]
