# Generated by Django 3.2.11 on 2022-02-25 11:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0015_auto_20220225_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Brief_Descrition',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
    ]
