# Generated by Django 3.2.11 on 2022-02-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0016_jobs_brief_descrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_text',
            name='img',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
