# Generated by Django 3.2.11 on 2022-03-16 04:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0017_brand_text_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=300)),
                ('Mess', tinymce.models.HTMLField()),
            ],
        ),
    ]
