# Generated by Django 3.2.11 on 2022-03-16 14:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0018_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Image')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('project_desc', tinymce.models.HTMLField(verbose_name='Project Description')),
                ('is_link', models.BooleanField(default=False, verbose_name='URL Active ?')),
                ('Url', models.CharField(max_length=300)),
            ],
        ),
    ]
