# Generated by Django 3.2.11 on 2022-03-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0019_projects_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects_data',
            name='Url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
