# Generated by Django 3.2.11 on 2022-03-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0020_alter_projects_data_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='Header Text')),
                ('sub', models.CharField(max_length=100, verbose_name='Sub text')),
            ],
        ),
    ]
