# Generated by Django 3.2.11 on 2022-03-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0021_project_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='tag',
            field=models.CharField(default=0, max_length=100, verbose_name='Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solutions_french',
            name='tag',
            field=models.CharField(default=0, max_length=100, verbose_name='Tag'),
            preserve_default=False,
        ),
    ]
