# Generated by Django 3.2.11 on 2022-03-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0022_auto_20220317_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_solutions',
            name='tag',
            field=models.CharField(default=0, max_length=100, verbose_name='Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_solutions_french',
            name='tag',
            field=models.CharField(default=0, max_length=100, verbose_name='Tag'),
            preserve_default=False,
        ),
    ]
