# Generated by Django 3.2.11 on 2022-03-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0023_auto_20220317_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_solutions',
            name='Service_name_english',
            field=models.CharField(default=0, max_length=300, verbose_name='Service Name (English)'),
            preserve_default=False,
        ),
    ]
