# Generated by Django 3.2.11 on 2022-03-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0024_sub_solutions_service_name_english'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_solutions',
            name='Service_name_english',
        ),
        migrations.AddField(
            model_name='sub_solutions_french',
            name='Service_name_english',
            field=models.CharField(default=0, max_length=300, verbose_name='Service Name (English)'),
            preserve_default=False,
        ),
    ]
