# Generated by Django 3.2.11 on 2022-03-18 02:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0025_auto_20220318_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_header_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='Header Text')),
                ('sub', models.CharField(max_length=100, verbose_name='Sub text')),
            ],
        ),
        migrations.CreateModel(
            name='projects_data_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Image')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('project_desc', tinymce.models.HTMLField(verbose_name='Project Description')),
                ('is_link', models.BooleanField(default=False, verbose_name='URL Active ?')),
                ('Url', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
