# Generated by Django 3.2.11 on 2022-03-18 02:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0026_project_header_french_projects_data_french'),
    ]

    operations = [
        migrations.CreateModel(
            name='corpo_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_desc', tinymce.models.HTMLField(verbose_name='Page Content')),
            ],
        ),
        migrations.CreateModel(
            name='corpo_data_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_desc', tinymce.models.HTMLField(verbose_name='Page Content')),
            ],
        ),
        migrations.CreateModel(
            name='corpo_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='Header Text')),
                ('sub', models.CharField(max_length=100, verbose_name='Sub text')),
            ],
        ),
        migrations.CreateModel(
            name='corpo_header_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='Header Text')),
                ('sub', models.CharField(max_length=100, verbose_name='Sub text')),
            ],
        ),
    ]
