# Generated by Django 3.2.11 on 2022-03-18 09:10

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0028_contact_info_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='corpo_sub_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Corp_Name', models.CharField(max_length=200, verbose_name='Sub Corporate Name')),
                ('Sub_Corp_Data', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='corpo_sub_data_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Corp_Name', models.CharField(max_length=200, verbose_name='Sub Corporate Name')),
                ('Sub_Corp_Data', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
    ]
