# Generated by Django 3.2.11 on 2022-03-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0029_corpo_sub_data_corpo_sub_data_french'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpo_sub_data',
            name='Sub_tag',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpo_sub_data_french',
            name='Sub_tag',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
