# Generated by Django 3.2.11 on 2022-04-09 18:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0030_auto_20220318_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='career_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_desc', tinymce.models.HTMLField(verbose_name='Page Content')),
            ],
        ),
        migrations.CreateModel(
            name='career_data_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_desc', tinymce.models.HTMLField(verbose_name='Page Content')),
            ],
        ),
        migrations.CreateModel(
            name='career_sub_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_career_Name', models.CharField(max_length=200, verbose_name='Sub Corporate Name')),
                ('Sub_career_Data', tinymce.models.HTMLField(verbose_name='Content')),
                ('Sub_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='career_sub_data_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_career_Name', models.CharField(max_length=200, verbose_name='Sub Corporate Name')),
                ('Sub_career_Data', tinymce.models.HTMLField(verbose_name='Content')),
                ('Sub_tag', models.CharField(max_length=100)),
            ],
        ),
    ]
