# Generated by Django 3.2.11 on 2022-04-15 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0032_career_header_career_header_french'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_sub_data',
            name='Sub_End_Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career_sub_data',
            name='Sub_Start_Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career_sub_data_french',
            name='Sub_End_Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career_sub_data_french',
            name='Sub_Start_Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
