# Generated by Django 3.2.11 on 2022-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0034_auto_20220415_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='career_training_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, verbose_name='Name')),
                ('Email', models.EmailField(max_length=200, verbose_name='Email')),
                ('Description', models.CharField(max_length=300, verbose_name='Training Name')),
                ('Mobile', models.IntegerField(verbose_name='Mobile')),
                ('amt', models.IntegerField(verbose_name='Amount')),
            ],
        ),
    ]
