# Generated by Django 3.2.11 on 2022-04-15 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0035_career_training_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_training_form',
            name='Submitted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
