# Generated by Django 3.2.11 on 2022-04-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helloworld', '0031_career_data_career_data_french_career_sub_data_career_sub_data_french'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_data1',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Project Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.projects_data',),
        ),
        migrations.CreateModel(
            name='project_data2',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Project Content (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.projects_data_french',),
        ),
        migrations.CreateModel(
            name='project_head1',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Project Header',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.project_header',),
        ),
        migrations.CreateModel(
            name='project_head2',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Project Header (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.project_header_french',),
        ),
    ]
