# Generated by Django 3.2.11 on 2022-02-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_aboutus_french_brand_text_french_contactmodel_address_french_contactmodel_email_french_contactmodel_'),
        ('partners', '0002_partner_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_Content_french',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Partner Content (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.sub_partners_french',),
        ),
        migrations.CreateModel(
            name='Partners_french',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Partner (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.p_artners_french',),
        ),
    ]
