# Generated by Django 3.2.11 on 2022-04-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0031_career_data_career_data_french_career_sub_data_career_sub_data_french'),
        ('partners', '0003_partner_content_french_partners_french'),
    ]

    operations = [
        migrations.CreateModel(
            name='part_text1',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Headers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.part_text',),
        ),
        migrations.CreateModel(
            name='part_text2',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Headers (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.part_text_french',),
        ),
    ]
