# Generated by Django 3.2.11 on 2022-04-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helloworld', '0033_auto_20220415_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='career_data1',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.career_data',),
        ),
        migrations.CreateModel(
            name='career_data2',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Content (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.career_data_french',),
        ),
        migrations.CreateModel(
            name='career_header1',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Header',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.career_header',),
        ),
        migrations.CreateModel(
            name='career_header2',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Header (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.career_header_french',),
        ),
        migrations.CreateModel(
            name='career_sub1',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Sub Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.career_sub_data',),
        ),
        migrations.CreateModel(
            name='career_sub2',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Sub Content (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.career_sub_data_french',),
        ),
    ]
