# Generated by Django 3.2.11 on 2022-04-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0035_career_training_form'),
        ('career_training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='career_form',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Training Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.career_training_form',),
        ),
    ]
