# Generated by Django 3.2.11 on 2022-02-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_aboutus_french_brand_text_french_contactmodel_address_french_contactmodel_email_french_contactmodel_'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_french',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Manage Home Page Content (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.home_content_french',),
        ),
        migrations.CreateModel(
            name='Hero_french',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Modify Hero (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.hero_text_french',),
        ),
        migrations.CreateModel(
            name='Logo_french',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Modify Logo (French)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('helloworld.brand_text_french',),
        ),
    ]
